language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

addons:
  apt:
    packages:
      - ldap-utils
      - slapd
      - gnutls-bin
      - ssl-cert

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - travis_retry composer update $COMPOSER_FLAGS --prefer-dist

before_script:
  - sudo ./tests/resources/openldap/setup.sh

script:
  - vendor/bin/phpspec run --no-interaction
  - vendor/bin/phpunit

jobs:
  allow_failures:
    -   php: 7.4snapshot

  include:
    -   stage: Code Quality
        php: 7.3
        env: PHPStan
        install: travis_retry composer install --prefer-dist
        script: vendor/bin/phpstan analyse